<Filter>
[KNKOD] = 
'0117'
or
[KNKOD] = 
'0127'
or
[KNKOD] = 
'0140'
or
[KNKOD] = 
'0188'
or
[KNKOD] = 
'0192'
or
[KNKOD] = 
'0305'
or
[KNKOD] = 
'0488'
or
[KNKOD] = 
'0560'
or
[KNKOD] = 
'0561'
or
[KNKOD] = 
'0583'
or
[KNKOD] = 
'0682'
or
[KNKOD] = 
'0683'
or
[KNKOD] = 
'0764'
or
[KNKOD] = 
'0765'
or
[KNKOD] = 
'0821'
or
[KNKOD] = 
'0881'
or
[KNKOD] = 
'0885'
or
[KNKOD] = 
'1383'
or
[KNKOD] = 
'1462'
or
[KNKOD] = 
'1980'
or
[KNKOD] = 
'2039'
or
[KNKOD] = 
'2161'
or
[KNKOD] = 
'2184'
or
[KNKOD] = 
'2282'
or
[KNKOD] = 
'2283'
or
[KNKOD] = 
'2284'
or
[KNKOD] = 
'2321'
or
[KNKOD] = 
'2326'
or
[KNKOD] = 
'2361'
or
[KNKOD] = 
'2421'
or
[KNKOD] = 
'2482'
or
[KNKOD] = 
'2513'
or
[KNKOD] = 
'2514'
or
[KNKOD] = 
'2518'
or
[KNKOD] = 
'2523'
or
[KNKOD] = 
'2584'
</Filter>
