<Filter>
[KNKOD] = 
'0115'
or
[KNKOD] = 
'0126'
or
[KNKOD] = 
'0139'
or
[KNKOD] = 
'0380'
or
[KNKOD] = 
'0381'
or
[KNKOD] = 
'0484'
or
[KNKOD] = 
'0580'
or
[KNKOD] = 
'0582'
or
[KNKOD] = 
'0617'
or
[KNKOD] = 
'0686'
or
[KNKOD] = 
'0860'
or
[KNKOD] = 
'0862'
or
[KNKOD] = 
'0883'
or
[KNKOD] = 
'0884'
or
[KNKOD] = 
'2082'
or
[KNKOD] = 
'2180'
or
[KNKOD] = 
'2303'
or
[KNKOD] = 
'2309'
or
[KNKOD] = 
'2313'
or
[KNKOD] = 
'2480'
or
[KNKOD] = 
'2581'
or
[KNKOD] = 
'2583'
</Filter>
