<Filter>
[KNKOD] = 
'0123'
or
[KNKOD] = 
'0180'
or
[KNKOD] = 
'0182'
or
[KNKOD] = 
'0481'
or
[KNKOD] = 
'0560'
or
[KNKOD] = 
'0684'
or
[KNKOD] = 
'0860'
or
[KNKOD] = 
'1060'
or
[KNKOD] = 
'1402'
or
[KNKOD] = 
'1441'
or
[KNKOD] = 
'1442'
or
[KNKOD] = 
'1447'
or
[KNKOD] = 
'1452'
or
[KNKOD] = 
'1481'
or
[KNKOD] = 
'1490'
or
[KNKOD] = 
'1491'
or
[KNKOD] = 
'1496'
or
[KNKOD] = 
'1760'
or
[KNKOD] = 
'1762'
or
[KNKOD] = 
'1784'
or
[KNKOD] = 
'1962'
or
[KNKOD] = 
'1984'
or
[KNKOD] = 
'2418'
or
[KNKOD] = 
'2422'
or
[KNKOD] = 
'2505'
</Filter>
