<Filter>
[KNKOD] = 
'0115'
or
[KNKOD] = 
'0117'
or
[KNKOD] = 
'0120'
or
[KNKOD] = 
'0125'
or
[KNKOD] = 
'0136'
or
[KNKOD] = 
'0181'
or
[KNKOD] = 
'0188'
or
[KNKOD] = 
'0191'
or
[KNKOD] = 
'0192'
or
[KNKOD] = 
'0360'
or
[KNKOD] = 
'0380'
or
[KNKOD] = 
'0381'
or
[KNKOD] = 
'0480'
or
[KNKOD] = 
'0484'
or
[KNKOD] = 
'0486'
or
[KNKOD] = 
'0580'
or
[KNKOD] = 
'0581'
or
[KNKOD] = 
'0583'
or
[KNKOD] = 
'0680'
or
[KNKOD] = 
'0780'
or
[KNKOD] = 
'0840'
or
[KNKOD] = 
'0861'
or
[KNKOD] = 
'0880'
or
[KNKOD] = 
'0883'
or
[KNKOD] = 
'0885'
or
[KNKOD] = 
'0980'
or
[KNKOD] = 
'1080'
or
[KNKOD] = 
'1081'
or
[KNKOD] = 
'1082'
or
[KNKOD] = 
'1083'
or
[KNKOD] = 
'1263'
or
[KNKOD] = 
'1265'
or
[KNKOD] = 
'1266'
or
[KNKOD] = 
'1276'
or
[KNKOD] = 
'1278'
or
[KNKOD] = 
'1281'
or
[KNKOD] = 
'1282'
or
[KNKOD] = 
'1283'
or
[KNKOD] = 
'1286'
or
[KNKOD] = 
'1287'
or
[KNKOD] = 
'1290'
or
[KNKOD] = 
'1291'
or
[KNKOD] = 
'1292'
or
[KNKOD] = 
'1293'
or
[KNKOD] = 
'1380'
or
[KNKOD] = 
'1381'
or
[KNKOD] = 
'1382'
or
[KNKOD] = 
'1383'
or
[KNKOD] = 
'1401'
or
[KNKOD] = 
'1421'
or
[KNKOD] = 
'1463'
or
[KNKOD] = 
'1485'
or
[KNKOD] = 
'1737'
or
[KNKOD] = 
'1766'
or
[KNKOD] = 
'1780'
or
[KNKOD] = 
'1880'
or
[KNKOD] = 
'1980'
or
[KNKOD] = 
'2021'
or
[KNKOD] = 
'2026'
or
[KNKOD] = 
'2029'
or
[KNKOD] = 
'2031'
or
[KNKOD] = 
'2061'
or
[KNKOD] = 
'2062'
or
[KNKOD] = 
'2080'
or
[KNKOD] = 
'2081'
or
[KNKOD] = 
'2082'
or
[KNKOD] = 
'2084'
or
[KNKOD] = 
'2161'
or
[KNKOD] = 
'2180'
or
[KNKOD] = 
'2181'
or
[KNKOD] = 
'2182'
or
[KNKOD] = 
'2183'
or
[KNKOD] = 
'2184'
or
[KNKOD] = 
'2280'
or
[KNKOD] = 
'2281'
or
[KNKOD] = 
'2282'
or
[KNKOD] = 
'2283'
or
[KNKOD] = 
'2284'
or
[KNKOD] = 
'2309'
or
[KNKOD] = 
'2313'
or
[KNKOD] = 
'2321'
or
[KNKOD] = 
'2326'
or
[KNKOD] = 
'2361'
or
[KNKOD] = 
'2380'
or
[KNKOD] = 
'2462'
or
[KNKOD] = 
'2480'
or
[KNKOD] = 
'2482'
or
[KNKOD] = 
'2514'
or
[KNKOD] = 
'2518'
or
[KNKOD] = 
'2521'
or
[KNKOD] = 
'2580'
or
[KNKOD] = 
'2581'
or
[KNKOD] = 
'2582'
or
[KNKOD] = 
'2584'
</Filter>
