<Filter>
[KNKOD] = 
'0138'
or
[KNKOD] = 
'0186'
or
[KNKOD] = 
'0488'
or
[KNKOD] = 
'0513'
or
[KNKOD] = 
'0584'
or
[KNKOD] = 
'0604'
or
[KNKOD] = 
'0617'
or
[KNKOD] = 
'0662'
or
[KNKOD] = 
'0665'
or
[KNKOD] = 
'0682'
or
[KNKOD] = 
'0821'
or
[KNKOD] = 
'1275'
or
[KNKOD] = 
'1493'
or
[KNKOD] = 
'1494'
or
[KNKOD] = 
'1861'
or
[KNKOD] = 
'1862'
or
[KNKOD] = 
'1904'
or
[KNKOD] = 
'1907'
or
[KNKOD] = 
'1983'
or
[KNKOD] = 
'2425'
or
[KNKOD] = 
'2481'
or
[KNKOD] = 
'2510'
</Filter>
