<Filter>
[KNKOD] = 
'0126'
or
[KNKOD] = 
'0319'
or
[KNKOD] = 
'0331'
or
[KNKOD] = 
'0461'
or
[KNKOD] = 
'0482'
or
[KNKOD] = 
'0562'
or
[KNKOD] = 
'0563'
or
[KNKOD] = 
'0582'
or
[KNKOD] = 
'0760'
or
[KNKOD] = 
'1257'
or
[KNKOD] = 
'1284'
or
[KNKOD] = 
'1315'
or
[KNKOD] = 
'1465'
or
[KNKOD] = 
'1470'
or
[KNKOD] = 
'1488'
or
[KNKOD] = 
'1489'
or
[KNKOD] = 
'1715'
or
[KNKOD] = 
'1730'
or
[KNKOD] = 
'1761'
or
[KNKOD] = 
'1764'
or
[KNKOD] = 
'1814'
or
[KNKOD] = 
'1863'
or
[KNKOD] = 
'2101'
or
[KNKOD] = 
'2132'
</Filter>
