#!/bin/bash
sed '
s|k="official_name"|k="name"|i
s|k="color"|k="colour"|i
s|k="colour" v="snow"|k="colour" v="#FFFAFA"|i
s|k="colour" v="GhostWhite"|k="colour" v="#F8F8FF"|i
s|k="colour" v="WhiteSmoke"|k="colour" v="#F5F5F5"|i
s|k="colour" v="gainsboro"|k="colour" v="#DCDCDC"|i
s|k="colour" v="FloralWhite"|k="colour" v="#FFFAF0"|i
s|k="colour" v="OldLace"|k="colour" v="#FDF5E6"|i
s|k="colour" v="linen"|k="colour" v="#FAF0E6"|i
s|k="colour" v="AntiqueWhite"|k="colour" v="#FAEBD7"|i
s|k="colour" v="PapayaWhip"|k="colour" v="#FFEFD5"|i
s|k="colour" v="BlanchedAlmond"|k="colour" v="#FFEBCD"|i
s|k="colour" v="bisque"|k="colour" v="#FFE4C4"|i
s|k="colour" v="PeachPuff"|k="colour" v="#FFDAB9"|i
s|k="colour" v="NavajoWhite"|k="colour" v="#FFDEAD"|i
s|k="colour" v="moccasin"|k="colour" v="#FFE4B5"|i
s|k="colour" v="cornsilk"|k="colour" v="#FFF8DC"|i
s|k="colour" v="ivory"|k="colour" v="#FFFFF0"|i
s|k="colour" v="LemonChiffon"|k="colour" v="#FFFACD"|i
s|k="colour" v="seashell"|k="colour" v="#FFF5EE"|i
s|k="colour" v="honeydew"|k="colour" v="#F0FFF0"|i
s|k="colour" v="MintCream"|k="colour" v="#F5FFFA"|i
s|k="colour" v="azure"|k="colour" v="#F0FFFF"|i
s|k="colour" v="AliceBlue"|k="colour" v="#F0F8FF"|i
s|k="colour" v="lavender"|k="colour" v="#E6E6FA"|i
s|k="colour" v="LavenderBlush"|k="colour" v="#FFF0F5"|i
s|k="colour" v="MistyRose"|k="colour" v="#FFE4E1"|i
s|k="colour" v="white"|k="colour" v="#FFFFFF"|i
s|k="colour" v="black"|k="colour" v="#000000"|i
s|k="colour" v="DarkSlateGray"|k="colour" v="#2F4F4F"|i
s|k="colour" v="DimGray"|k="colour" v="#696969"|i
s|k="colour" v="SlateGray"|k="colour" v="#708090"|i
s|k="colour" v="LightSlateGray"|k="colour" v="#778899"|i
s|k="colour" v="gray"|k="colour" v="#BEBEBE"|i
s|k="colour" v="LightGrey"|k="colour" v="#D3D3D3"|i
s|k="colour" v="MidnightBlue"|k="colour" v="#191970"|i
s|k="colour" v="navy"|k="colour" v="#000080"|i
s|k="colour" v="NavyBlue"|k="colour" v="#000080"|i
s|k="colour" v="CornflowerBlue"|k="colour" v="#6495ED"|i
s|k="colour" v="DarkSlateBlue"|k="colour" v="#483D8B"|i
s|k="colour" v="SlateBlue"|k="colour" v="#6A5ACD"|i
s|k="colour" v="MediumSlateBlue"|k="colour" v="#7B68EE"|i
s|k="colour" v="LightSlateBlue"|k="colour" v="#8470FF"|i
s|k="colour" v="MediumBlue"|k="colour" v="#0000CD"|i
s|k="colour" v="RoyalBlue"|k="colour" v="#4169E1"|i
s|k="colour" v="blue"|k="colour" v="#0000FF"|i
s|k="colour" v="DodgerBlue"|k="colour" v="#1E90FF"|i
s|k="colour" v="DeepSkyBlue"|k="colour" v="#00BFFF"|i
s|k="colour" v="SkyBlue"|k="colour" v="#87CEEB"|i
s|k="colour" v="LightSkyBlue"|k="colour" v="#87CEFA"|i
s|k="colour" v="SteelBlue"|k="colour" v="#4682B4"|i
s|k="colour" v="LightSteelBlue"|k="colour" v="#B0C4DE"|i
s|k="colour" v="LightBlue"|k="colour" v="#ADD8E6"|i
s|k="colour" v="PowderBlue"|k="colour" v="#B0E0E6"|i
s|k="colour" v="PaleTurquoise"|k="colour" v="#AFEEEE"|i
s|k="colour" v="DarkTurquoise"|k="colour" v="#00CED1"|i
s|k="colour" v="MediumTurquoise"|k="colour" v="#48D1CC"|i
s|k="colour" v="turquoise"|k="colour" v="#40E0D0"|i
s|k="colour" v="cyan"|k="colour" v="#00FFFF"|i
s|k="colour" v="LightCyan"|k="colour" v="#E0FFFF"|i
s|k="colour" v="CadetBlue"|k="colour" v="#5F9EA0"|i
s|k="colour" v="MediumAquamarine"|k="colour" v="#66CDAA"|i
s|k="colour" v="aquamarine"|k="colour" v="#7FFFD4"|i
s|k="colour" v="DarkGreen"|k="colour" v="#006400"|i
s|k="colour" v="DarkOliveGreen"|k="colour" v="#556B2F"|i
s|k="colour" v="DarkSeaGreen"|k="colour" v="#8FBC8F"|i
s|k="colour" v="SeaGreen"|k="colour" v="#2E8B57"|i
s|k="colour" v="MediumSeaGreen"|k="colour" v="#3CB371"|i
s|k="colour" v="LightSeaGreen"|k="colour" v="#20B2AA"|i
s|k="colour" v="PaleGreen"|k="colour" v="#98FB98"|i
s|k="colour" v="SpringGreen"|k="colour" v="#00FF7F"|i
s|k="colour" v="LawnGreen"|k="colour" v="#7CFC00"|i
s|k="colour" v="green"|k="colour" v="#00FF00"|i
s|k="colour" v="chartreuse"|k="colour" v="#7FFF00"|i
s|k="colour" v="MediumSpringGreen"|k="colour" v="#00FA9A"|i
s|k="colour" v="GreenYellow"|k="colour" v="#ADFF2F"|i
s|k="colour" v="LimeGreen"|k="colour" v="#32CD32"|i
s|k="colour" v="YellowGreen"|k="colour" v="#9ACD32"|i
s|k="colour" v="ForestGreen"|k="colour" v="#228B22"|i
s|k="colour" v="OliveDrab"|k="colour" v="#6B8E23"|i
s|k="colour" v="DarkKhaki"|k="colour" v="#BDB76B"|i
s|k="colour" v="khaki"|k="colour" v="#F0E68C"|i
s|k="colour" v="PaleGoldenrod"|k="colour" v="#EEE8AA"|i
s|k="colour" v="LightGoldenrodYellow"|k="colour" v="#FAFAD2"|i
s|k="colour" v="LightYellow"|k="colour" v="#FFFFE0"|i
s|k="colour" v="yellow"|k="colour" v="#FFFF00"|i
s|k="colour" v="gold"|k="colour" v="#FFD700"|i
s|k="colour" v="LightGoldenrod"|k="colour" v="#EEDD82"|i
s|k="colour" v="goldenrod"|k="colour" v="#DAA520"|i
s|k="colour" v="DarkGoldenrod"|k="colour" v="#B8860B"|i
s|k="colour" v="RosyBrown"|k="colour" v="#BC8F8F"|i
s|k="colour" v="IndianRed"|k="colour" v="#CD5C5C"|i
s|k="colour" v="SaddleBrown"|k="colour" v="#8B4513"|i
s|k="colour" v="sienna"|k="colour" v="#A0522D"|i
s|k="colour" v="peru"|k="colour" v="#CD853F"|i
s|k="colour" v="burlywood"|k="colour" v="#DEB887"|i
s|k="colour" v="beige"|k="colour" v="#F5F5DC"|i
s|k="colour" v="wheat"|k="colour" v="#F5DEB3"|i
s|k="colour" v="SandyBrown"|k="colour" v="#F4A460"|i
s|k="colour" v="tan"|k="colour" v="#D2B48C"|i
s|k="colour" v="chocolate"|k="colour" v="#D2691E"|i
s|k="colour" v="firebrick"|k="colour" v="#B22222"|i
s|k="colour" v="brown"|k="colour" v="#A52A2A"|i
s|k="colour" v="DarkSalmon"|k="colour" v="#E9967A"|i
s|k="colour" v="salmon"|k="colour" v="#FA8072"|i
s|k="colour" v="LightSalmon"|k="colour" v="#FFA07A"|i
s|k="colour" v="orange"|k="colour" v="#FFA500"|i
s|k="colour" v="DarkOrange"|k="colour" v="#FF8C00"|i
s|k="colour" v="coral"|k="colour" v="#FF7F50"|i
s|k="colour" v="LightCoral"|k="colour" v="#F08080"|i
s|k="colour" v="tomato"|k="colour" v="#FF6347"|i
s|k="colour" v="OrangeRed"|k="colour" v="#FF4500"|i
s|k="colour" v="red"|k="colour" v="#FF0000"|i
s|k="colour" v="HotPink"|k="colour" v="#FF69B4"|i
s|k="colour" v="DeepPink"|k="colour" v="#FF1493"|i
s|k="colour" v="pink"|k="colour" v="#FFC0CB"|i
s|k="colour" v="LightPink"|k="colour" v="#FFB6C1"|i
s|k="colour" v="PaleVioletRed"|k="colour" v="#DB7093"|i
s|k="colour" v="maroon"|k="colour" v="#B03060"|i
s|k="colour" v="MediumVioletRed"|k="colour" v="#C71585"|i
s|k="colour" v="VioletRed"|k="colour" v="#D02090"|i
s|k="colour" v="magenta"|k="colour" v="#FF00FF"|i
s|k="colour" v="violet"|k="colour" v="#EE82EE"|i
s|k="colour" v="plum"|k="colour" v="#DDA0DD"|i
s|k="colour" v="orchid"|k="colour" v="#DA70D6"|i
s|k="colour" v="MediumOrchid"|k="colour" v="#BA55D3"|i
s|k="colour" v="DarkOrchid"|k="colour" v="#9932CC"|i
s|k="colour" v="DarkViolet"|k="colour" v="#9400D3"|i
s|k="colour" v="BlueViolet"|k="colour" v="#8A2BE2"|i
s|k="colour" v="purple"|k="colour" v="#A020F0"|i
s|k="colour" v="MediumPurple"|k="colour" v="#9370DB"|i
s|k="colour" v="thistle"|k="colour" v="#D8BFD8"|i
s|k="colour" v="snow1"|k="colour" v="#FFFAFA"|i
s|k="colour" v="snow2"|k="colour" v="#EEE9E9"|i
s|k="colour" v="snow3"|k="colour" v="#CDC9C9"|i
s|k="colour" v="snow4"|k="colour" v="#8B8989"|i
s|k="colour" v="seashell1"|k="colour" v="#FFF5EE"|i
s|k="colour" v="seashell2"|k="colour" v="#EEE5DE"|i
s|k="colour" v="seashell3"|k="colour" v="#CDC5BF"|i
s|k="colour" v="seashell4"|k="colour" v="#8B8682"|i
s|k="colour" v="AntiqueWhite1"|k="colour" v="#FFEFDB"|i
s|k="colour" v="AntiqueWhite2"|k="colour" v="#EEDFCC"|i
s|k="colour" v="AntiqueWhite3"|k="colour" v="#CDC0B0"|i
s|k="colour" v="AntiqueWhite4"|k="colour" v="#8B8378"|i
s|k="colour" v="bisque1"|k="colour" v="#FFE4C4"|i
s|k="colour" v="bisque2"|k="colour" v="#EED5B7"|i
s|k="colour" v="bisque3"|k="colour" v="#CDB79E"|i
s|k="colour" v="bisque4"|k="colour" v="#8B7D6B"|i
s|k="colour" v="PeachPuff1"|k="colour" v="#FFDAB9"|i
s|k="colour" v="PeachPuff2"|k="colour" v="#EECBAD"|i
s|k="colour" v="PeachPuff3"|k="colour" v="#CDAF95"|i
s|k="colour" v="PeachPuff4"|k="colour" v="#8B7765"|i
s|k="colour" v="NavajoWhite1"|k="colour" v="#FFDEAD"|i
s|k="colour" v="NavajoWhite2"|k="colour" v="#EECFA1"|i
s|k="colour" v="NavajoWhite3"|k="colour" v="#CDB38B"|i
s|k="colour" v="NavajoWhite4"|k="colour" v="#8B795E"|i
s|k="colour" v="LemonChiffon1"|k="colour" v="#FFFACD"|i
s|k="colour" v="LemonChiffon2"|k="colour" v="#EEE9BF"|i
s|k="colour" v="LemonChiffon3"|k="colour" v="#CDC9A5"|i
s|k="colour" v="LemonChiffon4"|k="colour" v="#8B8970"|i
s|k="colour" v="cornsilk1"|k="colour" v="#FFF8DC"|i
s|k="colour" v="cornsilk2"|k="colour" v="#EEE8CD"|i
s|k="colour" v="cornsilk3"|k="colour" v="#CDC8B1"|i
s|k="colour" v="cornsilk4"|k="colour" v="#8B8878"|i
s|k="colour" v="ivory1"|k="colour" v="#FFFFF0"|i
s|k="colour" v="ivory2"|k="colour" v="#EEEEE0"|i
s|k="colour" v="ivory3"|k="colour" v="#CDCDC1"|i
s|k="colour" v="ivory4"|k="colour" v="#8B8B83"|i
s|k="colour" v="honeydew1"|k="colour" v="#F0FFF0"|i
s|k="colour" v="honeydew2"|k="colour" v="#E0EEE0"|i
s|k="colour" v="honeydew3"|k="colour" v="#C1CDC1"|i
s|k="colour" v="honeydew4"|k="colour" v="#838B83"|i
s|k="colour" v="LavenderBlush1"|k="colour" v="#FFF0F5"|i
s|k="colour" v="LavenderBlush2"|k="colour" v="#EEE0E5"|i
s|k="colour" v="LavenderBlush3"|k="colour" v="#CDC1C5"|i
s|k="colour" v="LavenderBlush4"|k="colour" v="#8B8386"|i
s|k="colour" v="MistyRose1"|k="colour" v="#FFE4E1"|i
s|k="colour" v="MistyRose2"|k="colour" v="#EED5D2"|i
s|k="colour" v="MistyRose3"|k="colour" v="#CDB7B5"|i
s|k="colour" v="MistyRose4"|k="colour" v="#8B7D7B"|i
s|k="colour" v="azure1"|k="colour" v="#F0FFFF"|i
s|k="colour" v="azure2"|k="colour" v="#E0EEEE"|i
s|k="colour" v="azure3"|k="colour" v="#C1CDCD"|i
s|k="colour" v="azure4"|k="colour" v="#838B8B"|i
s|k="colour" v="SlateBlue1"|k="colour" v="#836FFF"|i
s|k="colour" v="SlateBlue2"|k="colour" v="#7A67EE"|i
s|k="colour" v="SlateBlue3"|k="colour" v="#6959CD"|i
s|k="colour" v="SlateBlue4"|k="colour" v="#473C8B"|i
s|k="colour" v="RoyalBlue1"|k="colour" v="#4876FF"|i
s|k="colour" v="RoyalBlue2"|k="colour" v="#436EEE"|i
s|k="colour" v="RoyalBlue3"|k="colour" v="#3A5FCD"|i
s|k="colour" v="RoyalBlue4"|k="colour" v="#27408B"|i
s|k="colour" v="blue1"|k="colour" v="#0000FF"|i
s|k="colour" v="blue2"|k="colour" v="#0000EE"|i
s|k="colour" v="blue3"|k="colour" v="#0000CD"|i
s|k="colour" v="blue4"|k="colour" v="#00008B"|i
s|k="colour" v="DodgerBlue1"|k="colour" v="#1E90FF"|i
s|k="colour" v="DodgerBlue2"|k="colour" v="#1C86EE"|i
s|k="colour" v="DodgerBlue3"|k="colour" v="#1874CD"|i
s|k="colour" v="DodgerBlue4"|k="colour" v="#104E8B"|i
s|k="colour" v="SteelBlue1"|k="colour" v="#63B8FF"|i
s|k="colour" v="SteelBlue2"|k="colour" v="#5CACEE"|i
s|k="colour" v="SteelBlue3"|k="colour" v="#4F94CD"|i
s|k="colour" v="SteelBlue4"|k="colour" v="#36648B"|i
s|k="colour" v="DeepSkyBlue1"|k="colour" v="#00BFFF"|i
s|k="colour" v="DeepSkyBlue2"|k="colour" v="#00B2EE"|i
s|k="colour" v="DeepSkyBlue3"|k="colour" v="#009ACD"|i
s|k="colour" v="DeepSkyBlue4"|k="colour" v="#00688B"|i
s|k="colour" v="SkyBlue1"|k="colour" v="#87CEFF"|i
s|k="colour" v="SkyBlue2"|k="colour" v="#7EC0EE"|i
s|k="colour" v="SkyBlue3"|k="colour" v="#6CA6CD"|i
s|k="colour" v="SkyBlue4"|k="colour" v="#4A708B"|i
s|k="colour" v="LightSkyBlue1"|k="colour" v="#B0E2FF"|i
s|k="colour" v="LightSkyBlue2"|k="colour" v="#A4D3EE"|i
s|k="colour" v="LightSkyBlue3"|k="colour" v="#8DB6CD"|i
s|k="colour" v="LightSkyBlue4"|k="colour" v="#607B8B"|i
s|k="colour" v="SlateGray1"|k="colour" v="#C6E2FF"|i
s|k="colour" v="SlateGray2"|k="colour" v="#B9D3EE"|i
s|k="colour" v="SlateGray3"|k="colour" v="#9FB6CD"|i
s|k="colour" v="SlateGray4"|k="colour" v="#6C7B8B"|i
s|k="colour" v="LightSteelBlue1"|k="colour" v="#CAE1FF"|i
s|k="colour" v="LightSteelBlue2"|k="colour" v="#BCD2EE"|i
s|k="colour" v="LightSteelBlue3"|k="colour" v="#A2B5CD"|i
s|k="colour" v="LightSteelBlue4"|k="colour" v="#6E7B8B"|i
s|k="colour" v="LightBlue1"|k="colour" v="#BFEFFF"|i
s|k="colour" v="LightBlue2"|k="colour" v="#B2DFEE"|i
s|k="colour" v="LightBlue3"|k="colour" v="#9AC0CD"|i
s|k="colour" v="LightBlue4"|k="colour" v="#68838B"|i
s|k="colour" v="LightCyan1"|k="colour" v="#E0FFFF"|i
s|k="colour" v="LightCyan2"|k="colour" v="#D1EEEE"|i
s|k="colour" v="LightCyan3"|k="colour" v="#B4CDCD"|i
s|k="colour" v="LightCyan4"|k="colour" v="#7A8B8B"|i
s|k="colour" v="PaleTurquoise1"|k="colour" v="#BBFFFF"|i
s|k="colour" v="PaleTurquoise2"|k="colour" v="#AEEEEE"|i
s|k="colour" v="PaleTurquoise3"|k="colour" v="#96CDCD"|i
s|k="colour" v="PaleTurquoise4"|k="colour" v="#668B8B"|i
s|k="colour" v="CadetBlue1"|k="colour" v="#98F5FF"|i
s|k="colour" v="CadetBlue2"|k="colour" v="#8EE5EE"|i
s|k="colour" v="CadetBlue3"|k="colour" v="#7AC5CD"|i
s|k="colour" v="CadetBlue4"|k="colour" v="#53868B"|i
s|k="colour" v="turquoise1"|k="colour" v="#00F5FF"|i
s|k="colour" v="turquoise2"|k="colour" v="#00E5EE"|i
s|k="colour" v="turquoise3"|k="colour" v="#00C5CD"|i
s|k="colour" v="turquoise4"|k="colour" v="#00868B"|i
s|k="colour" v="cyan1"|k="colour" v="#00FFFF"|i
s|k="colour" v="cyan2"|k="colour" v="#00EEEE"|i
s|k="colour" v="cyan3"|k="colour" v="#00CDCD"|i
s|k="colour" v="cyan4"|k="colour" v="#008B8B"|i
s|k="colour" v="DarkSlateGray1"|k="colour" v="#97FFFF"|i
s|k="colour" v="DarkSlateGray2"|k="colour" v="#8DEEEE"|i
s|k="colour" v="DarkSlateGray3"|k="colour" v="#79CDCD"|i
s|k="colour" v="DarkSlateGray4"|k="colour" v="#528B8B"|i
s|k="colour" v="aquamarine1"|k="colour" v="#7FFFD4"|i
s|k="colour" v="aquamarine2"|k="colour" v="#76EEC6"|i
s|k="colour" v="aquamarine3"|k="colour" v="#66CDAA"|i
s|k="colour" v="aquamarine4"|k="colour" v="#458B74"|i
s|k="colour" v="DarkSeaGreen1"|k="colour" v="#C1FFC1"|i
s|k="colour" v="DarkSeaGreen2"|k="colour" v="#B4EEB4"|i
s|k="colour" v="DarkSeaGreen3"|k="colour" v="#9BCD9B"|i
s|k="colour" v="DarkSeaGreen4"|k="colour" v="#698B69"|i
s|k="colour" v="SeaGreen1"|k="colour" v="#54FF9F"|i
s|k="colour" v="SeaGreen2"|k="colour" v="#4EEE94"|i
s|k="colour" v="SeaGreen3"|k="colour" v="#43CD80"|i
s|k="colour" v="SeaGreen4"|k="colour" v="#2E8B57"|i
s|k="colour" v="PaleGreen1"|k="colour" v="#9AFF9A"|i
s|k="colour" v="PaleGreen2"|k="colour" v="#90EE90"|i
s|k="colour" v="PaleGreen3"|k="colour" v="#7CCD7C"|i
s|k="colour" v="PaleGreen4"|k="colour" v="#548B54"|i
s|k="colour" v="SpringGreen1"|k="colour" v="#00FF7F"|i
s|k="colour" v="SpringGreen2"|k="colour" v="#00EE76"|i
s|k="colour" v="SpringGreen3"|k="colour" v="#00CD66"|i
s|k="colour" v="SpringGreen4"|k="colour" v="#008B45"|i
s|k="colour" v="green1"|k="colour" v="#00FF00"|i
s|k="colour" v="green2"|k="colour" v="#00EE00"|i
s|k="colour" v="green3"|k="colour" v="#00CD00"|i
s|k="colour" v="green4"|k="colour" v="#008B00"|i
s|k="colour" v="chartreuse1"|k="colour" v="#7FFF00"|i
s|k="colour" v="chartreuse2"|k="colour" v="#76EE00"|i
s|k="colour" v="chartreuse3"|k="colour" v="#66CD00"|i
s|k="colour" v="chartreuse4"|k="colour" v="#458B00"|i
s|k="colour" v="OliveDrab1"|k="colour" v="#C0FF3E"|i
s|k="colour" v="OliveDrab2"|k="colour" v="#B3EE3A"|i
s|k="colour" v="OliveDrab3"|k="colour" v="#9ACD32"|i
s|k="colour" v="OliveDrab4"|k="colour" v="#698B22"|i
s|k="colour" v="DarkOliveGreen1"|k="colour" v="#CAFF70"|i
s|k="colour" v="DarkOliveGreen2"|k="colour" v="#BCEE68"|i
s|k="colour" v="DarkOliveGreen3"|k="colour" v="#A2CD5A"|i
s|k="colour" v="DarkOliveGreen4"|k="colour" v="#6E8B3D"|i
s|k="colour" v="khaki1"|k="colour" v="#FFF68F"|i
s|k="colour" v="khaki2"|k="colour" v="#EEE685"|i
s|k="colour" v="khaki3"|k="colour" v="#CDC673"|i
s|k="colour" v="khaki4"|k="colour" v="#8B864E"|i
s|k="colour" v="LightGoldenrod1"|k="colour" v="#FFEC8B"|i
s|k="colour" v="LightGoldenrod2"|k="colour" v="#EEDC82"|i
s|k="colour" v="LightGoldenrod3"|k="colour" v="#CDBE70"|i
s|k="colour" v="LightGoldenrod4"|k="colour" v="#8B814C"|i
s|k="colour" v="LightYellow1"|k="colour" v="#FFFFE0"|i
s|k="colour" v="LightYellow2"|k="colour" v="#EEEED1"|i
s|k="colour" v="LightYellow3"|k="colour" v="#CDCDB4"|i
s|k="colour" v="LightYellow4"|k="colour" v="#8B8B7A"|i
s|k="colour" v="yellow1"|k="colour" v="#FFFF00"|i
s|k="colour" v="yellow2"|k="colour" v="#EEEE00"|i
s|k="colour" v="yellow3"|k="colour" v="#CDCD00"|i
s|k="colour" v="yellow4"|k="colour" v="#8B8B00"|i
s|k="colour" v="gold1"|k="colour" v="#FFD700"|i
s|k="colour" v="gold2"|k="colour" v="#EEC900"|i
s|k="colour" v="gold3"|k="colour" v="#CDAD00"|i
s|k="colour" v="gold4"|k="colour" v="#8B7500"|i
s|k="colour" v="goldenrod1"|k="colour" v="#FFC125"|i
s|k="colour" v="goldenrod2"|k="colour" v="#EEB422"|i
s|k="colour" v="goldenrod3"|k="colour" v="#CD9B1D"|i
s|k="colour" v="goldenrod4"|k="colour" v="#8B6914"|i
s|k="colour" v="DarkGoldenrod1"|k="colour" v="#FFB90F"|i
s|k="colour" v="DarkGoldenrod2"|k="colour" v="#EEAD0E"|i
s|k="colour" v="DarkGoldenrod3"|k="colour" v="#CD950C"|i
s|k="colour" v="DarkGoldenrod4"|k="colour" v="#8B6508"|i
s|k="colour" v="RosyBrown1"|k="colour" v="#FFC1C1"|i
s|k="colour" v="RosyBrown2"|k="colour" v="#EEB4B4"|i
s|k="colour" v="RosyBrown3"|k="colour" v="#CD9B9B"|i
s|k="colour" v="RosyBrown4"|k="colour" v="#8B6969"|i
s|k="colour" v="IndianRed1"|k="colour" v="#FF6A6A"|i
s|k="colour" v="IndianRed2"|k="colour" v="#EE6363"|i
s|k="colour" v="IndianRed3"|k="colour" v="#CD5555"|i
s|k="colour" v="IndianRed4"|k="colour" v="#8B3A3A"|i
s|k="colour" v="sienna1"|k="colour" v="#FF8247"|i
s|k="colour" v="sienna2"|k="colour" v="#EE7942"|i
s|k="colour" v="sienna3"|k="colour" v="#CD6839"|i
s|k="colour" v="sienna4"|k="colour" v="#8B4726"|i
s|k="colour" v="burlywood1"|k="colour" v="#FFD39B"|i
s|k="colour" v="burlywood2"|k="colour" v="#EEC591"|i
s|k="colour" v="burlywood3"|k="colour" v="#CDAA7D"|i
s|k="colour" v="burlywood4"|k="colour" v="#8B7355"|i
s|k="colour" v="wheat1"|k="colour" v="#FFE7BA"|i
s|k="colour" v="wheat2"|k="colour" v="#EED8AE"|i
s|k="colour" v="wheat3"|k="colour" v="#CDBA96"|i
s|k="colour" v="wheat4"|k="colour" v="#8B7E66"|i
s|k="colour" v="tan1"|k="colour" v="#FFA54F"|i
s|k="colour" v="tan2"|k="colour" v="#EE9A49"|i
s|k="colour" v="tan3"|k="colour" v="#CD853F"|i
s|k="colour" v="tan4"|k="colour" v="#8B5A2B"|i
s|k="colour" v="chocolate1"|k="colour" v="#FF7F24"|i
s|k="colour" v="chocolate2"|k="colour" v="#EE7621"|i
s|k="colour" v="chocolate3"|k="colour" v="#CD661D"|i
s|k="colour" v="chocolate4"|k="colour" v="#8B4513"|i
s|k="colour" v="firebrick1"|k="colour" v="#FF3030"|i
s|k="colour" v="firebrick2"|k="colour" v="#EE2C2C"|i
s|k="colour" v="firebrick3"|k="colour" v="#CD2626"|i
s|k="colour" v="firebrick4"|k="colour" v="#8B1A1A"|i
s|k="colour" v="brown1"|k="colour" v="#FF4040"|i
s|k="colour" v="brown2"|k="colour" v="#EE3B3B"|i
s|k="colour" v="brown3"|k="colour" v="#CD3333"|i
s|k="colour" v="brown4"|k="colour" v="#8B2323"|i
s|k="colour" v="salmon1"|k="colour" v="#FF8C69"|i
s|k="colour" v="salmon2"|k="colour" v="#EE8262"|i
s|k="colour" v="salmon3"|k="colour" v="#CD7054"|i
s|k="colour" v="salmon4"|k="colour" v="#8B4C39"|i
s|k="colour" v="LightSalmon1"|k="colour" v="#FFA07A"|i
s|k="colour" v="LightSalmon2"|k="colour" v="#EE9572"|i
s|k="colour" v="LightSalmon3"|k="colour" v="#CD8162"|i
s|k="colour" v="LightSalmon4"|k="colour" v="#8B5742"|i
s|k="colour" v="orange1"|k="colour" v="#FFA500"|i
s|k="colour" v="orange2"|k="colour" v="#EE9A00"|i
s|k="colour" v="orange3"|k="colour" v="#CD8500"|i
s|k="colour" v="orange4"|k="colour" v="#8B5A00"|i
s|k="colour" v="DarkOrange1"|k="colour" v="#FF7F00"|i
s|k="colour" v="DarkOrange2"|k="colour" v="#EE7600"|i
s|k="colour" v="DarkOrange3"|k="colour" v="#CD6600"|i
s|k="colour" v="DarkOrange4"|k="colour" v="#8B4500"|i
s|k="colour" v="coral1"|k="colour" v="#FF7256"|i
s|k="colour" v="coral2"|k="colour" v="#EE6A50"|i
s|k="colour" v="coral3"|k="colour" v="#CD5B45"|i
s|k="colour" v="coral4"|k="colour" v="#8B3E2F"|i
s|k="colour" v="tomato1"|k="colour" v="#FF6347"|i
s|k="colour" v="tomato2"|k="colour" v="#EE5C42"|i
s|k="colour" v="tomato3"|k="colour" v="#CD4F39"|i
s|k="colour" v="tomato4"|k="colour" v="#8B3626"|i
s|k="colour" v="OrangeRed1"|k="colour" v="#FF4500"|i
s|k="colour" v="OrangeRed2"|k="colour" v="#EE4000"|i
s|k="colour" v="OrangeRed3"|k="colour" v="#CD3700"|i
s|k="colour" v="OrangeRed4"|k="colour" v="#8B2500"|i
s|k="colour" v="red1"|k="colour" v="#FF0000"|i
s|k="colour" v="red2"|k="colour" v="#EE0000"|i
s|k="colour" v="red3"|k="colour" v="#CD0000"|i
s|k="colour" v="red4"|k="colour" v="#8B0000"|i
s|k="colour" v="DeepPink1"|k="colour" v="#FF1493"|i
s|k="colour" v="DeepPink2"|k="colour" v="#EE1289"|i
s|k="colour" v="DeepPink3"|k="colour" v="#CD1076"|i
s|k="colour" v="DeepPink4"|k="colour" v="#8B0A50"|i
s|k="colour" v="HotPink1"|k="colour" v="#FF6EB4"|i
s|k="colour" v="HotPink2"|k="colour" v="#EE6AA7"|i
s|k="colour" v="HotPink3"|k="colour" v="#CD6090"|i
s|k="colour" v="HotPink4"|k="colour" v="#8B3A62"|i
s|k="colour" v="pink1"|k="colour" v="#FFB5C5"|i
s|k="colour" v="pink2"|k="colour" v="#EEA9B8"|i
s|k="colour" v="pink3"|k="colour" v="#CD919E"|i
s|k="colour" v="pink4"|k="colour" v="#8B636C"|i
s|k="colour" v="LightPink1"|k="colour" v="#FFAEB9"|i
s|k="colour" v="LightPink2"|k="colour" v="#EEA2AD"|i
s|k="colour" v="LightPink3"|k="colour" v="#CD8C95"|i
s|k="colour" v="LightPink4"|k="colour" v="#8B5F65"|i
s|k="colour" v="PaleVioletRed1"|k="colour" v="#FF82AB"|i
s|k="colour" v="PaleVioletRed2"|k="colour" v="#EE799F"|i
s|k="colour" v="PaleVioletRed3"|k="colour" v="#CD6889"|i
s|k="colour" v="PaleVioletRed4"|k="colour" v="#8B475D"|i
s|k="colour" v="maroon1"|k="colour" v="#FF34B3"|i
s|k="colour" v="maroon2"|k="colour" v="#EE30A7"|i
s|k="colour" v="maroon3"|k="colour" v="#CD2990"|i
s|k="colour" v="maroon4"|k="colour" v="#8B1C62"|i
s|k="colour" v="VioletRed1"|k="colour" v="#FF3E96"|i
s|k="colour" v="VioletRed2"|k="colour" v="#EE3A8C"|i
s|k="colour" v="VioletRed3"|k="colour" v="#CD3278"|i
s|k="colour" v="VioletRed4"|k="colour" v="#8B2252"|i
s|k="colour" v="magenta1"|k="colour" v="#FF00FF"|i
s|k="colour" v="magenta2"|k="colour" v="#EE00EE"|i
s|k="colour" v="magenta3"|k="colour" v="#CD00CD"|i
s|k="colour" v="magenta4"|k="colour" v="#8B008B"|i
s|k="colour" v="orchid1"|k="colour" v="#FF83FA"|i
s|k="colour" v="orchid2"|k="colour" v="#EE7AE9"|i
s|k="colour" v="orchid3"|k="colour" v="#CD69C9"|i
s|k="colour" v="orchid4"|k="colour" v="#8B4789"|i
s|k="colour" v="plum1"|k="colour" v="#FFBBFF"|i
s|k="colour" v="plum2"|k="colour" v="#EEAEEE"|i
s|k="colour" v="plum3"|k="colour" v="#CD96CD"|i
s|k="colour" v="plum4"|k="colour" v="#8B668B"|i
s|k="colour" v="MediumOrchid1"|k="colour" v="#E066FF"|i
s|k="colour" v="MediumOrchid2"|k="colour" v="#D15FEE"|i
s|k="colour" v="MediumOrchid3"|k="colour" v="#B452CD"|i
s|k="colour" v="MediumOrchid4"|k="colour" v="#7A378B"|i
s|k="colour" v="DarkOrchid1"|k="colour" v="#BF3EFF"|i
s|k="colour" v="DarkOrchid2"|k="colour" v="#B23AEE"|i
s|k="colour" v="DarkOrchid3"|k="colour" v="#9A32CD"|i
s|k="colour" v="DarkOrchid4"|k="colour" v="#68228B"|i
s|k="colour" v="purple1"|k="colour" v="#9B30FF"|i
s|k="colour" v="purple2"|k="colour" v="#912CEE"|i
s|k="colour" v="purple3"|k="colour" v="#7D26CD"|i
s|k="colour" v="purple4"|k="colour" v="#551A8B"|i
s|k="colour" v="MediumPurple1"|k="colour" v="#AB82FF"|i
s|k="colour" v="MediumPurple2"|k="colour" v="#9F79EE"|i
s|k="colour" v="MediumPurple3"|k="colour" v="#8968CD"|i
s|k="colour" v="MediumPurple4"|k="colour" v="#5D478B"|i
s|k="colour" v="thistle1"|k="colour" v="#FFE1FF"|i
s|k="colour" v="thistle2"|k="colour" v="#EED2EE"|i
s|k="colour" v="thistle3"|k="colour" v="#CDB5CD"|i
s|k="colour" v="thistle4"|k="colour" v="#8B7B8B"|i
s|k="colour" v="DarkGray"|k="colour" v="#A9A9A9"|i
s|k="colour" v="DarkBlue"|k="colour" v="#00008B"|i
s|k="colour" v="DarkCyan"|k="colour" v="#008B8B"|i
s|k="colour" v="DarkMagenta"|k="colour" v="#8B008B"|i
s|k="colour" v="DarkRed"|k="colour" v="#8B0000"|i
s|k="colour" v="LightGreen"|k="colour" v="#90EE90"|i' input.osm>output.osm
